name: Backend Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**' 
  workflow_run:
    workflows: ["Check-code"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Introduce error in script
        run: |
          # Introduce a deliberate syntax error
          echho "This is an intentional error"  

      - name: ssh to server update code and restart node server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script_stop: true
          script: |
            
            
            # Gracefully stop Node.js server if it's already running
            if pgrep -x "node" > /dev/null
            then
              pkill -x node
            fi
            
            cd colleague-portal
            git stash
            git pull origin main

            cd
            echo "Updating app.properties on the server..."
            echo "db.server=${{ secrets.DB_SERVER }}" > ~/colleague-portal/backend/server/config/app.properties
            echo "db.name=${{ secrets.DB_NAME }}" >> ~/colleague-portal/backend/server/config/app.properties
            echo "db.user=${{ secrets.DB_USER }}" >> ~/colleague-portal/backend/server/config/app.properties
            echo "db.password=${{ secrets.DB_PASSWORD }}" >> ~/colleague-portal/backend/server/config/app.properties
            echo "db.port=${{ secrets.DB_PORT }}" >> ~/colleague-portal/backend/server/config/app.properties
            echo "db.connectionLimit=${{ secrets.DB_CONNECTION_LIMIT }}" >> ~/colleague-portal/backend/server/config/app.properties

            cd
            
            # Install backend dependencies and start the Node.js server
            cd colleague-portal/backend/server/
            npm install
            nohup node app.js &> backend.log &

