name: Backend Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'production'
  workflow_run:
    workflows: ["Check-code"]
    types:
      - completed

jobs:
  check-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies and run tests (Backend)
        working-directory: backend/server
        run: |
          npm install
          nohup node app.js &> backend.log &

      - name: Install dependencies and run tests (Frontend)
        working-directory: frontend
        run: |
          npm install
          nohup npm start &> frontend.log &

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
         
      - name: ssh to server update code and restart node server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script_stop: true
          script: |
            
            
            # Gracefully stop Node.js server if it's already running
            echo "Stopping Node.js server if it's running"
            if pgrep -x "node" > /dev/null
            then
              echo "server is running"
              sudo pkill -x node
            else
              echo "Server is not running"
            fi
            
            
            echo "Navigating to project directory"
            cd colleague-portal
            
            echo "Stash any local changes"
            git stash
            
            echo "Pull latest changes from main branch"
            git pull origin main

            
            echo "Updating app.properties on the server..."
            echo "db.server=${{ secrets.DB_SERVER }}" > ~/colleague-portal/backend/server/config/app.properties
            echo "db.name=${{ secrets.DB_NAME }}" >> ~/colleague-portal/backend/server/config/app.properties
            echo "db.user=${{ secrets.DB_USER }}" >> ~/colleague-portal/backend/server/config/app.properties
            echo "db.password=${{ secrets.DB_PASSWORD }}" >> ~/colleague-portal/backend/server/config/app.properties
            echo "db.port=${{ secrets.DB_PORT }}" >> ~/colleague-portal/backend/server/config/app.properties
            echo "db.connectionLimit=${{ secrets.DB_CONNECTION_LIMIT }}" >> ~/colleague-portal/backend/server/config/app.properties

          
            
            # Install backend dependencies and start the Node.js server
            echo "Installing backend dependencies"
            cd ~/colleague-portal/backend/server/
            npm install
            
            echo "Starting the server"
            nohup node app.js &> backend.log &
            echo "Server started"
