name: Hello World Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print current directory
        run: pwd

      - name: List files in current directory
        run: ls -l

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          cd colleague-portal

          # Stop Node.js server if it's already running
          if pgrep -x "node" > /dev/null; then
            pkill -x node
          fi

          # Pull the latest changes from main
          git pull origin main

          # Install backend dependencies
          cd backend/server/
          npm install

          # Run backend tests
          node test

          # Install frontend dependencies
          cd ../../frontend
          npm install

          # Run frontend tests
          npm test

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Print current directory
        run: pwd

      - name: List files in current directory
        run: ls -l

      - name: SSH into Server and restart
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # Add debugging information
            pwd
            ls -l

            # Gracefully stop Node.js server if it's already running
            if pgrep -x "node" > /dev/null; then
              pkill -x node
            fi

            cd colleague-portal

            # Start the backend server
            cd backend/server/
            nohup node app.js &> backend.log &

            # Start the frontend server
            cd ../../frontend
            nohup npm start &> frontend.log



           

           


           
           
           
            
           
            
            

           

           
            
            
          

           
            

            


