name: Hello World Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: SSH into Server and restart
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd stavirsolutions
            git pull origin main
            cd colleague-portal/backend/server

            # Gracefully stop Node.js server if it's already running
            if pgrep -x "node" > /dev/null
            then
              pkill -x node
            fi

            # Install dependencies and start the Node.js server
            npm install
            nohup node app.js &> backend.log &
            cd
            cd stavirsolutions/colleague-portal/frontend
            nohup npm start &> frontend.log  &
            

            


