name: Hello World Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: SSH into Server and restart
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # Gracefully stop Node.js server if it's already running
            if pgrep -x "node" > /dev/null
            then
              pkill -x node
            fi
            cd stavirsolutions
            git pull origin main

            # Install backend dependencies and start the Node.js server
            cd colleague-portal/backend/server
            npm install
            nohup node app.js &> backend.log &

            # Install frontend dependencies and start the frontend server
            cd
            cd stavirsolutions/colleague-portal/frontend
            nohup npm start &> frontend.log &

            

            


