name: PR Build and Deploy

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
         

          # Stop Node.js server if it's already running
          if pgrep -x "node" > /dev/null
          then
            pkill -x node
          fi

           cd colleague-portal

          # Pull the latest changes from main
          git pull origin main

          # Start the backend server
          cd backend/server/
          nohup node app.js &> backend.log &

          # Start the frontend server
          cd
          cd colleague-portal/frontend
          nohup npm start &> frontend.log &

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Set up Node.js for deploy
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Deploy changes
        run: |
          

          # Stop Node.js server if it's already running
          if pgrep -x "node" > /dev/null
          then
            pkill -x node
          fi

          cd colleague-portal

          # Pull the latest changes from main
          git pull origin main

          # Start the backend server
          cd backend/server/
          nohup node app.js &> backend.log &

          # Start the frontend server
          cd 
          cd colleague-portal/frontend
          nohup npm start &> frontend.log &

            

           

           


           
           
           
            
           
            
            

           

           
            
            
          

           
            

            


