name: PR Validation

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_NAME: ${{ secrets.DB_NAME }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Backend Tests
      - name: Install Backend Dependencies
        working-directory: backend/server
        run: npm install
        
      - name: Run Backend Tests
        working-directory: backend/server
        run: |
          export DB_PORT=$DB_PORT
          export DB_USERNAME=$DB_NAME
          node app.js

      # Frontend Tests
      - name: Install Frontend Dependencies
        working-directory: frontend
        run: npm install

      - name: Start Frontend Server
        working-directory: frontend
        run: npm start

